import type {
  BusinessProfile,
  Product,
  Customer,
  Sale,
  Expense,
  Transaction,
  NetworkBusiness,
  BusinessNeed,
  BusinessListing,
  Enquiry,
  ChatConversation,
  ChatMessage,
  Notification,
  BusinessIdea,
  LocalOpportunity,
  GovScheme,
  BusinessPlan,
  RoadmapStep,
  LearnLesson,
  SimulatorInputs,
} from "./types";

export const initialBusinessProfile: BusinessProfile = {
  id: "biz-jaipur-heritage",
  name: "Jaipur Heritage",
  ownerName: "Prashant Sharma",
  phone: "+91 98290 12345",
  email: "prashant@jaipurheritage.in",
  location: "Sanganer, Jaipur, Rajasthan",
  category: "Artisan MSME & Textiles",
  description:
    "Handcrafted block-print textiles, eco-friendly cotton bags, and traditional Rajasthani indigo accessories made by local artisans.",
  stage: "growing",
  availableCapital: 200000,
  skills: ["Block Printing", "Tailoring", "Natural Dyeing", "Local Sourcing"],
  resources: ["Workshop Space (400 sq ft)", "2 Stitching Machines", "Local Artisan Network"],
  experience: "Intermediate",
  readinessScore: 78,
};

export const initialProducts: Product[] = [
  {
    id: "prod-1",
    name: "Cotton Bags",
    category: "Bags & Totes",
    currentStock: 24,
    lowStockThreshold: 10,
    purchaseCost: 280,
    sellingPrice: 480,
    unit: "pieces",
    description: "100% pure cotton handcrafted printed tote bags with reinforced handles.",
    emoji: "🛍️",
  },
  {
    id: "prod-2",
    name: "Indigo Tote Bags",
    category: "Bags & Totes",
    currentStock: 15,
    lowStockThreshold: 8,
    purchaseCost: 340,
    sellingPrice: 590,
    unit: "pieces",
    description: "Naturally dyed indigo bags with Dabu mud-resist block prints.",
    emoji: "👜",
  },
  {
    id: "prod-3",
    name: "Silk Scarves",
    category: "Apparel & Accessories",
    currentStock: 6,
    lowStockThreshold: 8,
    purchaseCost: 520,
    sellingPrice: 950,
    unit: "pieces",
    description: "Lightweight Chanderi silk dupattas and scarves with gold zari border.",
    emoji: "🧣",
  },
  {
    id: "prod-4",
    name: "Block Print Fabric",
    category: "Raw Material",
    currentStock: 45,
    lowStockThreshold: 15,
    purchaseCost: 140,
    sellingPrice: 240,
    unit: "meters",
    description: "Premium Cambric cotton running fabric with Bagru natural dye printing.",
    emoji: "🧵",
  },
  {
    id: "prod-5",
    name: "Handmade Paper Diaries",
    category: "Stationery",
    currentStock: 30,
    lowStockThreshold: 10,
    purchaseCost: 90,
    sellingPrice: 190,
    unit: "pieces",
    description: "Eco-friendly diary made of recycled cotton rag handmade paper with leather cord.",
    emoji: "📔",
  },
];

export const initialCustomers: Customer[] = [
  {
    id: "cust-1",
    name: "Ramesh Kumar",
    phone: "+91 94140 55214",
    location: "MI Road, Jaipur",
    totalSpent: 12400,
    ordersCount: 5,
    lastPurchaseDate: "2026-09-02",
    notes: "Retail boutique owner, buys Cotton Bags & Silk Scarves in small bundles.",
    loyaltyStatus: "VIP",
  },
  {
    id: "cust-2",
    name: "Anita Sharma",
    phone: "+91 98281 99023",
    location: "Vaishali Nagar, Jaipur",
    totalSpent: 4720,
    ordersCount: 2,
    lastPurchaseDate: "2026-08-28",
    notes: "Buys Indigo Tote Bags for corporate gifting.",
    loyaltyStatus: "Regular",
  },
  {
    id: "cust-3",
    name: "Sunil Joshi",
    phone: "+91 97845 11029",
    location: "Tonk Phatak, Jaipur",
    totalSpent: 1900,
    ordersCount: 1,
    lastPurchaseDate: "2026-08-20",
    notes: "Handmade diary and bag purchase.",
    loyaltyStatus: "New",
  },
  {
    id: "cust-4",
    name: "Meenakshi Rathore",
    phone: "+91 96024 88390",
    location: "C-Scheme, Jaipur",
    totalSpent: 8550,
    ordersCount: 3,
    lastPurchaseDate: "2026-08-15",
    notes: "Regularly orders Silk Scarves.",
    loyaltyStatus: "Regular",
  },
];

export const initialSales: Sale[] = [
  {
    id: "sale-1",
    invoiceNumber: "INV-2026-001",
    productId: "prod-1",
    productName: "Cotton Bags",
    quantity: 10,
    unitPrice: 480,
    totalAmount: 4800,
    customerId: "cust-1",
    customerName: "Ramesh Kumar",
    date: "2026-09-02",
    paymentMethod: "UPI",
    notes: "Delivered to MI Road store.",
  },
  {
    id: "sale-2",
    invoiceNumber: "INV-2026-002",
    productId: "prod-2",
    productName: "Indigo Tote Bags",
    quantity: 8,
    unitPrice: 590,
    totalAmount: 4720,
    customerId: "cust-2",
    customerName: "Anita Sharma",
    date: "2026-08-28",
    paymentMethod: "UPI",
    notes: "Festive corporate order.",
  },
  {
    id: "sale-3",
    invoiceNumber: "INV-2026-003",
    productId: "prod-3",
    productName: "Silk Scarves",
    quantity: 4,
    unitPrice: 950,
    totalAmount: 3800,
    customerId: "cust-4",
    customerName: "Meenakshi Rathore",
    date: "2026-08-25",
    paymentMethod: "Cash",
  },
  {
    id: "sale-4",
    invoiceNumber: "INV-2026-004",
    productId: "prod-4",
    productName: "Block Print Fabric",
    quantity: 20,
    unitPrice: 240,
    totalAmount: 4800,
    customerId: "cust-1",
    customerName: "Ramesh Kumar",
    date: "2026-08-18",
    paymentMethod: "Bank Transfer",
  },
];

export const initialExpenses: Expense[] = [
  {
    id: "exp-1",
    category: "Raw Material",
    amount: 5600,
    date: "2026-09-01",
    description: "Purchased 40 meters pure cambric cotton from Sanganer Weaver",
    paymentMethod: "UPI",
  },
  {
    id: "exp-2",
    category: "Packaging",
    amount: 1200,
    date: "2026-08-29",
    description: "Eco-friendly brown paper bags and tag ropes",
    paymentMethod: "Cash",
  },
  {
    id: "exp-3",
    category: "Salary / Wages",
    amount: 4500,
    date: "2026-08-25",
    description: "Weekly wages paid to 2 master block printers",
    paymentMethod: "UPI",
  },
  {
    id: "exp-4",
    category: "Transport & Fuel",
    amount: 650,
    date: "2026-08-22",
    description: "Delivery of wholesale textile roll from market",
    paymentMethod: "Cash",
  },
];

export const initialTransactions: Transaction[] = [
  {
    id: "tx-1",
    type: "sale",
    title: "Sale: 10x Cotton Bags",
    category: "Sales Revenue",
    amount: 4800,
    date: "2026-09-02",
    partyName: "Ramesh Kumar",
    paymentMethod: "UPI",
    status: "completed",
    referenceId: "sale-1",
  },
  {
    id: "tx-2",
    type: "expense",
    title: "Raw Material: Cotton Fabric",
    category: "Raw Material",
    amount: 5600,
    date: "2026-09-01",
    partyName: "Sanganer Textile Mill",
    paymentMethod: "UPI",
    status: "completed",
    referenceId: "exp-1",
  },
  {
    id: "tx-3",
    type: "expense",
    title: "Packaging Material",
    category: "Packaging",
    amount: 1200,
    date: "2026-08-29",
    partyName: "Jaipur Eco Packaging",
    paymentMethod: "Cash",
    status: "completed",
    referenceId: "exp-2",
  },
  {
    id: "tx-4",
    type: "sale",
    title: "Sale: 8x Indigo Tote Bags",
    category: "Sales Revenue",
    amount: 4720,
    date: "2026-08-28",
    partyName: "Anita Sharma",
    paymentMethod: "UPI",
    status: "completed",
    referenceId: "sale-2",
  },
  {
    id: "tx-5",
    type: "sale",
    title: "Sale: 4x Silk Scarves",
    category: "Sales Revenue",
    amount: 3800,
    date: "2026-08-25",
    partyName: "Meenakshi Rathore",
    paymentMethod: "Cash",
    status: "completed",
    referenceId: "sale-3",
  },
  {
    id: "tx-6",
    type: "expense",
    title: "Artisan Wages",
    category: "Salary / Wages",
    amount: 4500,
    date: "2026-08-25",
    partyName: "Master Block Printers",
    paymentMethod: "UPI",
    status: "completed",
    referenceId: "exp-3",
  },
  {
    id: "tx-7",
    type: "expense",
    title: "Transport & Fuel",
    category: "Transport & Fuel",
    amount: 650,
    date: "2026-08-22",
    partyName: "Local Porter",
    paymentMethod: "Cash",
    status: "completed",
    referenceId: "exp-4",
  },
  {
    id: "tx-8",
    type: "sale",
    title: "Sale: 20m Block Print Fabric",
    category: "Sales Revenue",
    amount: 4800,
    date: "2026-08-18",
    partyName: "Ramesh Kumar",
    paymentMethod: "Bank Transfer",
    status: "completed",
    referenceId: "sale-4",
  },
];

export const initialNetworkBusinesses: NetworkBusiness[] = [
  {
    id: "net-1",
    name: "Natural Dye Supplier",
    owner: "Bhanwar Lal",
    category: "Raw Material & Dyes",
    location: "Bagru Road, Jaipur",
    district: "Jaipur",
    distanceKm: 4.2,
    rating: 4.8,
    reviewsCount: 34,
    verified: true,
    phone: "+91 94140 88219",
    about: "Supplying 100% organic indigo, madder root (manjistha), turmeric, pomegranate peel and harda natural dye extracts.",
    products: ["Indigo Cakes", "Madder Root Powder", "Harda Powder", "Alum Mordant"],
    services: ["Dye Recipe Consultation", "Bulk Wholesale Supply"],
    isSupplier: true,
    isBuyer: false,
    badge: "Verified Supplier",
  },
  {
    id: "net-2",
    name: "Cotton Wholesale Sanganer",
    owner: "Gopal Cloth Traders",
    category: "Textile Mill & Fabric",
    location: "Main Market, Sanganer",
    district: "Jaipur",
    distanceKm: 2.1,
    rating: 4.9,
    reviewsCount: 52,
    verified: true,
    phone: "+91 98292 44101",
    about: "Direct mill wholesale distributor for 60x60 Cambric cotton, unbleached sheeting, poplin, and organic cotton rolls.",
    products: ["60x60 Cambric Cotton", "Canvas 10oz", "Organic Cotton Yarn (50kg+)", "Lining Fabric"],
    services: ["Custom Slitting", "Doorstep Delivery"],
    isSupplier: true,
    isBuyer: false,
    badge: "Top Rated",
  },
  {
    id: "net-3",
    name: "Jaipur Eco Packaging",
    owner: "Vikas Aggarwal",
    category: "Packaging Materials",
    location: "Sitapura Industrial Area, Jaipur",
    district: "Jaipur",
    distanceKm: 6.8,
    rating: 4.6,
    reviewsCount: 28,
    verified: true,
    phone: "+91 97830 77412",
    about: "Biodegradable corrugated boxes, kraft paper mailing envelopes, customized cotton string tags, and water-activated tape.",
    products: ["Kraft Boxes", "Custom Printed Tags", "Cloth Drawstring Bags", "Honeycomb Wrap"],
    services: ["Custom Branding Stamp", "Sample Pack"],
    isSupplier: true,
    isBuyer: false,
    badge: "Fast Dispatch",
  },
  {
    id: "net-4",
    name: "Handmade Retailer & Boutique",
    owner: "Pooja Singhania",
    category: "Retail Buyer & Gift Store",
    location: "Civil Lines, Jaipur",
    district: "Jaipur",
    distanceKm: 8.5,
    rating: 4.9,
    reviewsCount: 41,
    verified: true,
    phone: "+91 99280 33819",
    about: "High-end curated boutique sourcing direct from rural craftspeople and MSMEs. Looking for sustainable bags, stoles and brass crafts.",
    products: ["Curated Gift Hampers", "Artisanal Home Linen"],
    services: ["Bulk Purchase", "Consignment Display"],
    isSupplier: false,
    isBuyer: true,
    badge: "Bulk Buyer",
  },
  {
    id: "net-5",
    name: "Marwar Handicraft Export Hub",
    owner: "Kailash Choudhary",
    category: "Export & B2B Buyer",
    location: "Mansarovar, Jaipur",
    district: "Jaipur",
    distanceKm: 5.4,
    rating: 4.7,
    reviewsCount: 65,
    verified: true,
    phone: "+91 94133 66782",
    about: "Aggregator sourcing Indian artisan crafts for European and US boutique buyers. Monthly recurring demand for 500+ pieces.",
    products: ["Export Certified Linen", "Indigo Cushion Covers", "Block Printed Quilts"],
    services: ["Export Documentation", "Quality Inspection"],
    isSupplier: false,
    isBuyer: true,
    badge: "Global Exporter",
  },
];

export const initialNeeds: BusinessNeed[] = [
  {
    id: "need-1",
    item: "50kg Organic Raw Cotton",
    category: "Raw Material",
    quantity: 50,
    unit: "kg",
    location: "Sanganer, Jaipur",
    budget: 12000,
    requiredDate: "2026-09-20",
    status: "active",
    notes: "Need chemical-free GOTS certified cotton yarn or lint for weaving tote bags.",
    createdDate: "2026-09-04",
  },
  {
    id: "need-2",
    item: "Wooden Printing Blocks (Floral motifs)",
    category: "Tools & Equipment",
    quantity: 6,
    unit: "sets",
    location: "Sanganer, Jaipur",
    budget: 3500,
    requiredDate: "2026-09-15",
    status: "active",
    notes: "Teakwood hand-carved blocks for traditional Bagru print collection.",
    createdDate: "2026-09-03",
  },
];

export const initialListings: BusinessListing[] = [
  {
    id: "list-1",
    title: "Surplus Pure Indigo Dyed Cambric (30 meters)",
    category: "Fabric",
    quantity: 30,
    unit: "meters",
    price: 210,
    location: "Sanganer, Jaipur",
    description: "Deep natural indigo dyed cambric 60x60 cotton. Excellent for tops, dresses or lining.",
    dateAdded: "2026-09-03",
    status: "active",
    contactPhone: "+91 98290 12345",
  },
  {
    id: "list-2",
    title: "Handmade Paper Gift Boxes (Pack of 50)",
    category: "Packaging",
    quantity: 50,
    unit: "boxes",
    price: 35,
    location: "Sanganer, Jaipur",
    description: "Rigid handmade paper gift boxes with gold foil motif. Ready stock.",
    dateAdded: "2026-08-30",
    status: "active",
    contactPhone: "+91 98290 12345",
  },
];

export const initialEnquiries: Enquiry[] = [
  {
    id: "enq-1",
    toBusinessId: "net-2",
    toBusinessName: "Cotton Wholesale Sanganer",
    needId: "need-1",
    subject: "Request for 50kg Organic Cotton",
    message: "Namaste Gopal ji, we need 50kg organic cambric cotton fabric rolls by next week for our bag production. Can you share best wholesale rate?",
    status: "replied",
    date: "2026-09-04",
    unread: false,
  },
  {
    id: "enq-2",
    toBusinessId: "net-4",
    toBusinessName: "Handmade Retailer & Boutique",
    subject: "Sample Catalog for Cotton & Indigo Bags",
    message: "Namaste Pooja ji, sharing our artisanal block-print bag catalog for your upcoming festive curation.",
    status: "in_discussion",
    date: "2026-09-03",
    unread: true,
  },
];

export const initialConversations: ChatConversation[] = [
  {
    id: "conv-1",
    businessId: "net-2",
    businessName: "Cotton Wholesale Sanganer",
    businessCategory: "Textile Mill & Fabric",
    businessLocation: "Main Market, Sanganer",
    lastMessage: "Haan Prashant ji, 50kg roll ready hai. ₹220/kg lag jayega with delivery.",
    lastMessageTime: "Today, 11:30 AM",
    unreadCount: 1,
    enquirySubject: "Request for 50kg Organic Cotton",
  },
  {
    id: "conv-2",
    businessId: "net-4",
    businessName: "Handmade Retailer & Boutique",
    businessCategory: "Retail Buyer & Gift Store",
    businessLocation: "Civil Lines, Jaipur",
    lastMessage: "Your indigo tote samples look very good! Can we place an initial order for 25 bags?",
    lastMessageTime: "Yesterday",
    unreadCount: 0,
    enquirySubject: "Sample Catalog for Cotton & Indigo Bags",
  },
  {
    id: "conv-3",
    businessId: "net-1",
    businessName: "Natural Dye Supplier",
    businessCategory: "Raw Material & Dyes",
    businessLocation: "Bagru Road, Jaipur",
    lastMessage: "Fresh batch of pure indigo cakes has arrived from Tamil Nadu.",
    lastMessageTime: "2 days ago",
    unreadCount: 0,
    enquirySubject: "Indigo dye availability",
  },
];

export const initialMessages: Record<string, ChatMessage[]> = {
  "conv-1": [
    {
      id: "msg-1-1",
      conversationId: "conv-1",
      senderId: "me",
      senderName: "Prashant Sharma",
      isMe: true,
      text: "Namaste Gopal ji, we need 50kg organic cambric cotton fabric rolls by next week for our bag production. Can you share best wholesale rate?",
      timestamp: "10:15 AM",
      enquiryContext: "Enquiry: Request for 50kg Organic Cotton",
    },
    {
      id: "msg-1-2",
      conversationId: "conv-1",
      senderId: "net-2",
      senderName: "Cotton Wholesale Sanganer",
      isMe: false,
      text: "Namaste Prashant ji! Humare paas 60x60 GOTS certified organic cambric cotton ready stock mein hai.",
      timestamp: "10:45 AM",
    },
    {
      id: "msg-1-3",
      conversationId: "conv-1",
      senderId: "net-2",
      senderName: "Cotton Wholesale Sanganer",
      isMe: false,
      text: "Haan Prashant ji, 50kg roll ready hai. ₹220/kg lag jayega with delivery.",
      timestamp: "11:30 AM",
    },
  ],
  "conv-2": [
    {
      id: "msg-2-1",
      conversationId: "conv-2",
      senderId: "me",
      senderName: "Prashant Sharma",
      isMe: true,
      text: "Namaste Pooja ji, sharing our artisanal block-print bag catalog for your upcoming festive curation.",
      timestamp: "Sep 3, 2:00 PM",
    },
    {
      id: "msg-2-2",
      conversationId: "conv-2",
      senderId: "net-4",
      senderName: "Pooja Singhania",
      isMe: false,
      text: "Your indigo tote samples look very good! Can we place an initial order for 25 bags?",
      timestamp: "Sep 3, 4:30 PM",
    },
  ],
  "conv-3": [
    {
      id: "msg-3-1",
      conversationId: "conv-3",
      senderId: "net-1",
      senderName: "Bhanwar Lal",
      isMe: false,
      text: "Fresh batch of pure indigo cakes has arrived from Tamil Nadu.",
      timestamp: "Sep 2, 9:15 AM",
    },
  ],
};

export const initialNotifications: Notification[] = [
  {
    id: "notif-1",
    type: "low_stock",
    title: "Low Stock Alert: Silk Scarves",
    body: "Silk Scarves ka stock sirf 6 bacha hai (Threshold: 8). Stock Mangwayein ya production plan karein.",
    timestamp: "1 hour ago",
    unread: true,
    linkUrl: "/my-business?tab=stock",
    linkText: "Check Stock",
    actionType: "stock_alert",
  },
  {
    id: "notif-2",
    type: "message",
    title: "New message from Cotton Wholesale Sanganer",
    body: "Gopal ji replied: 'Haan Prashant ji, 50kg roll ready hai. ₹220/kg lag jayega with delivery.'",
    timestamp: "3 hours ago",
    unread: true,
    linkUrl: "/network?tab=messages",
    linkText: "Open Chat",
  },
  {
    id: "notif-3",
    type: "scheme",
    title: "PM Vishwakarma Scheme Subsidy Open",
    body: "Artisans in Rajasthan can apply for ₹15,000 tool kit incentive and 5% interest collateral-free credit.",
    timestamp: "1 day ago",
    unread: true,
    linkUrl: "/loans-schemes",
    linkText: "View Scheme",
  },
  {
    id: "notif-4",
    type: "insight",
    title: "Business Growth Insight",
    body: "Aapka profit margin is mahine 48% raha hai. Cotton Bags is your top revenue contributor (₹4,800).",
    timestamp: "2 days ago",
    unread: false,
    linkUrl: "/reports",
    linkText: "View Report",
  },
];

export const initialBusinessIdeas: BusinessIdea[] = [
  {
    id: "idea-1",
    title: "Eco-Friendly Cotton & Tote Bag Manufacturing",
    titleHindi: "इको-फ्रेंडली कॉटन और टोट बैग निर्माण",
    category: "Textiles & Crafts",
    investmentMin: 50000,
    investmentMax: 150000,
    expectedDemand: "Very High",
    feasibilityScore: 92,
    competition: "Medium",
    requiredSkills: ["Stitching / Tailoring", "Basic Pattern Cutting", "Quality Checking"],
    resourcesNeeded: ["2 Industrial Sewing Machines", "Cutting Table", "Wholesale Cotton Sourcing"],
    description: "Produce durable cloth bags for retail shops, organic grocery stores, and corporate gifting as plastic alternatives.",
    whyItWorks: "Bans on single-use plastic and rising consumer preference for sustainable carry bags create steady year-round local demand.",
    keySteps: [
      "Source 10oz canvas and unbleached cambric cloth from local wholesale market.",
      "Hire 2 local tailors on piece-rate basis.",
      "Partner with 5 nearby grocery and apparel retailers for recurring orders.",
      "Offer custom screen-printed logo options for brand orders.",
    ],
  },
  {
    id: "idea-2",
    title: "Herbal & Organic Spice Grinding & Packaging",
    titleHindi: "शुद्ध जैविक मसाला पिसाई व पैकेजिंग",
    category: "Food & Agri-Processing",
    investmentMin: 80000,
    investmentMax: 200000,
    expectedDemand: "High",
    feasibilityScore: 86,
    competition: "Low",
    requiredSkills: ["Spice Grading", "Hygienic Packaging", "FSSAI Registration"],
    resourcesNeeded: ["2HP Stainless Steel Pulverizer", "Pouch Sealing Machine", "Digital Weighing Scale"],
    description: "Purchase whole farm-fresh turmeric, coriander, cumin and red chilies directly from farmers, grind in clean batch conditions, and pack in branded pouches.",
    whyItWorks: "Town and village households strongly distrust adulterated market spices and eagerly pay fair prices for freshly ground local spices.",
    keySteps: [
      "Procure whole spices directly from Mandi during peak harvest season.",
      "Install pulverizer unit in home or workshop space.",
      "Obtain basic FSSAI food license.",
      "Distribute 100g and 500g pouches to local Kirana shops and residential colonies.",
    ],
  },
  {
    id: "idea-3",
    title: "Solar-Powered Mobile Cold Storage / Tiffin Delivery",
    titleHindi: "सोलर कोल्ड स्टोरेज व टिफिन सर्विस",
    category: "Services & Logistics",
    investmentMin: 60000,
    investmentMax: 180000,
    expectedDemand: "High",
    feasibilityScore: 84,
    competition: "Low",
    requiredSkills: ["Cooking Management", "Route Planning", "Customer Service"],
    resourcesNeeded: ["Commercial Kitchen Space", "Insulated Delivery Containers", "Two-Wheeler"],
    description: "Home-style healthy lunch and dinner tiffin delivery service catering to bank staff, hospital workers, small offices and students.",
    whyItWorks: "High influx of working professionals in semi-urban hubs creates an unmet need for hygienic, affordable daily meals.",
    keySteps: [
      "Standardize a 4-item balanced nutritious menu (Roti, Dal, Sabzi, Rice/Salad).",
      "Offer monthly subscription passes (₹2,200 - ₹3,000/month).",
      "Distribute free trial meals to nearby bank branches and coaching centers.",
      "Use WhatsApp group for daily meal confirmations and payments.",
    ],
  },
  {
    id: "idea-4",
    title: "Handmade Paper Products & Stationery",
    titleHindi: "हस्तनिर्मित कागज डायरी व स्टेशनरी",
    category: "Artisan & Paper Crafts",
    investmentMin: 40000,
    investmentMax: 120000,
    expectedDemand: "High",
    feasibilityScore: 88,
    competition: "Low",
    requiredSkills: ["Book Binding", "Paper Folding", "Packaging"],
    resourcesNeeded: ["Cotton Rag Paper Sheets", "Paper Cutter", "Screen Print Frame"],
    description: "Manufacture artisanal diaries, wedding invitation paper, gift bags, and eco-stationery from cotton hosiery waste pulp.",
    whyItWorks: "Strong aesthetic appeal with premium profit margins (60%+), highly suited for Jaipur and Rajasthan tourist markets and exports.",
    keySteps: [
      "Procure raw handmade sheets from Sanganer paper artisans.",
      "Design hardcover journals with traditional fabric spine bindings.",
      "List on local craft exhibitions, boutique stores, and Pragati Network.",
    ],
  },
  {
    id: "idea-5",
    title: "Custom Tailoring & Boutique Finishing Center",
    titleHindi: "कस्टम टेलरिंग व बुटीक फिनिशिंग सेंटर",
    category: "Textiles & Fashion",
    investmentMin: 70000,
    investmentMax: 220000,
    expectedDemand: "Very High",
    feasibilityScore: 90,
    competition: "Medium",
    requiredSkills: ["Blouse & Kurta Cutting", "Interlock Machine Operation", "Hand Embroidery"],
    resourcesNeeded: ["2 High-Speed Motorized Machines", "1 Overlock/Interlock Machine", "Fitting Mirror"],
    description: "Women-led bespoke tailoring studio providing precision fitting, alteration, and designer blouse/suit stitching with fast turnaround.",
    whyItWorks: "Local women consistently face delayed deliveries from general tailors; a reliable, specialized service captures loyal recurring customers.",
    keySteps: [
      "Set up convenient, clean studio space in residential market hub.",
      "Provide transparent fixed price list with 3-day delivery guarantee.",
      "Offer doorstep fabric pickup and trial delivery service.",
    ],
  },
];

export const initialLocalOpportunities: LocalOpportunity[] = [
  {
    id: "opp-1",
    title: "Unmet Demand for Organic Cotton Carry Bags",
    titleHindi: "कॉटन बैग्स की स्थानीय भारी मांग",
    category: "Textiles & Retail Supplies",
    location: "Sanganer & Mansarovar, Jaipur",
    radiusKm: 5,
    gapDescription: "Over 85 grocery, sweet shops and clothing stores in a 5km radius currently buy plastic bags or sub-standard non-woven bags from far off suppliers.",
    feasibilityScore: 91,
    potentialMonthlyRevenue: 65000,
    targetAudience: "Local retail merchants, boutique owners, organic grocers",
    nearbyCompetitionCount: 2,
    demandTrend: "High Demand",
  },
  {
    id: "opp-2",
    title: "Fresh Unadulterated Cold-Pressed Mustard & Sesame Oil",
    titleHindi: "शुद्ध कच्ची घानी सरसों व तिल का तेल",
    category: "Agri-Processing & Food",
    location: "Sanganer Mandi Area",
    radiusKm: 8,
    gapDescription: "No traditional wood-press (Lakdi Ghani) cold-pressed oil extraction unit within 8 km. High consumer demand for pure cooking oil.",
    feasibilityScore: 87,
    potentialMonthlyRevenue: 95000,
    targetAudience: "Health-conscious families, sweet makers, local restaurants",
    nearbyCompetitionCount: 1,
    demandTrend: "Rising",
  },
  {
    id: "opp-3",
    title: "Institutional Cleaning & Natural Floor Wash Supply",
    titleHindi: "प्राकृतिक क्लीनिंग व फिनाइल सप्लाई",
    category: "Chemical & Home Care",
    location: "Sitapura Industrial & Institutional Zone",
    radiusKm: 10,
    gapDescription: "Schools, clinics, and industrial manufacturing units in Sitapura spend heavily on branded cleaning agents with high transport costs.",
    feasibilityScore: 82,
    potentialMonthlyRevenue: 52000,
    targetAudience: "Schools, factories, small hospitals, commercial complexes",
    nearbyCompetitionCount: 3,
    demandTrend: "Steady",
  },
  {
    id: "opp-4",
    title: "Artisanal Wedding Gifting & Packaging Hampers",
    titleHindi: "शादी-समारोह हैंडमेड गिफ्ट हैंपर्स",
    category: "Gifting & Crafts",
    location: "Vaishali Nagar & C-Scheme",
    radiusKm: 12,
    gapDescription: "High wedding season demand for handcrafted Rajasthani block-printed gift trays, mithai boxes, and dry fruit pouches.",
    feasibilityScore: 89,
    potentialMonthlyRevenue: 120000,
    targetAudience: "Wedding planners, event managers, corporate clients",
    nearbyCompetitionCount: 4,
    demandTrend: "High Demand",
  },
];

export const initialGovSchemes: GovScheme[] = [
  {
    id: "scheme-1",
    name: "Pradhan Mantri MUDRA Yojana (PMMY)",
    nameHindi: "प्रधानमंत्री मुद्रा योजना (Shishu / Kishor / Tarun)",
    ministry: "Ministry of Finance, Govt of India",
    maxAmount: 1000000,
    subsidyPct: 0,
    interestRate: "8.5% - 11.5% p.a. (Collateral-Free)",
    eligibility: [
      "Any Indian citizen with a non-farm business idea or existing micro enterprise",
      "Shishu: Loans up to ₹50,000 for starting out",
      "Kishor: Loans ₹50,001 to ₹5,00,000 for purchasing equipment & inventory",
      "Tarun: Loans ₹5,00,001 to ₹10,00,000 for enterprise scaling",
    ],
    description: "Collateral-free institutional credit to non-corporate, non-farm small/micro enterprises through Commercial Banks, RRBs, Small Finance Banks, and MFIs.",
    keyBenefits: [
      "No collateral or third-party guarantor required",
      "Mudra Card for flexible working capital withdrawal",
      "Affordable repayment tenure up to 5 years",
      "Low processing fees",
    ],
    documentsRequired: [
      "Aadhaar Card & PAN Card",
      "Proof of Business Address (Electricity Bill / Rent Agreement)",
      "Quotation of Machinery / Raw Material to be purchased",
      "Bank Account Statement for past 6 months",
    ],
    applySteps: [
      "Prepare your Pragati Business Plan and machinery quotation.",
      "Visit any public sector bank, Gramin Bank or apply on the official Udyamimitra portal.",
      "Submit Mudra Loan Application Form with KYC documents.",
      "Bank verifies business premises and sanctions loan within 7-14 working days.",
    ],
    category: "Mudra",
    officialUrl: "https://www.mudra.org.in",
  },
  {
    id: "scheme-2",
    name: "Prime Minister's Employment Generation Programme (PMEGP)",
    nameHindi: "प्रधानमंत्री रोजगार सृजन कार्यक्रम (PMEGP Subsidy)",
    ministry: "Ministry of MSME, Govt of India (KVIC)",
    maxAmount: 5000000,
    subsidyPct: 35,
    interestRate: "Bank Base Rate + 1.5% (with 25-35% Margin Money Subsidy)",
    eligibility: [
      "Individuals aged 18+ years",
      "Minimum 8th pass for manufacturing projects above ₹10 Lakh",
      "Rural area enterprises receive up to 35% government capital subsidy",
      "Urban area enterprises receive up to 25% subsidy",
    ],
    description: "Credit-linked subsidy programme to generate self-employment opportunities through establishment of micro-enterprises in non-farm sector.",
    keyBenefits: [
      "Massive 25% to 35% government subsidy on total project cost",
      "Project cost up to ₹50 Lakh for manufacturing, ₹20 Lakh for service units",
      "Own contribution only 5% for special categories (Women, SC/ST, Rural)",
      "Includes mandatory Entrepreneurship Development Training (EDP)",
    ],
    documentsRequired: [
      "Detailed Project Report (DPR / Business Plan)",
      "Educational qualification certificate (8th/10th mark sheet)",
      "Caste / Special category certificate (if applicable)",
      "Rural area certificate signed by Sarpanch / Gram Sevak",
    ],
    applySteps: [
      "Generate Project Report using Pragati Business Simulator & Plan Builder.",
      "Apply online on the official KVIC PMEGP portal (kviconline.gov.in).",
      "Application is reviewed by District Level Task Force Committee (DLTFC).",
      "Loan is sanctioned by participating bank; subsidy is locked in 3-year TDR.",
    ],
    category: "PMEGP",
    officialUrl: "https://www.kviconline.gov.in",
  },
  {
    id: "scheme-3",
    name: "PM Vishwakarma Scheme",
    nameHindi: "पीएम विश्वकर्मा योजना (Artisans & Craftsmen)",
    ministry: "Ministry of MSME & Ministry of Skill Development",
    maxAmount: 300000,
    subsidyPct: 0,
    interestRate: "Concessional 5% fixed interest (Collateral Free)",
    eligibility: [
      "Traditional artisans and craftsmen working in 18 notified trades (Tailor, Weaver, Potter, Carpenter, Blacksmith, Cobbler, etc.)",
      "Minimum age 18 years; family beneficiary limit of 1 person",
      "Engaged in trade on self-employment basis",
    ],
    description: "Holistic end-to-end support for rural and urban traditional artisans including skill upgradation, toolkit incentive, collateral-free credit, and digital transaction incentives.",
    keyBenefits: [
      "₹15,000 grant for modern toolkits and equipment",
      "Collateral-free credit: Tranche 1 (₹1,00,000 for 18 months), Tranche 2 (₹2,00,000 for 30 months)",
      "Extremely low 5% fixed interest rate with 8% interest subvention paid by Govt",
      "₹1 per digital transaction incentive (up to 100 transactions/month)",
      "PM Vishwakarma Certificate & ID card",
    ],
    documentsRequired: [
      "Aadhaar Card linked with active mobile number",
      "Bank Account details (Passbook copy / cancelled cheque)",
      "Ration Card or Family details",
      "Self-declaration of traditional artisan trade",
    ],
    applySteps: [
      "Visit nearest Common Service Centre (CSC) for Aadhaar biometric verification.",
      "Gram Panchayat or Urban Local Body verifies applicant.",
      "Complete 5-7 days basic skill training with ₹500/day stipend.",
      "Receive ₹15,000 toolkit e-voucher and apply for ₹1 Lakh collateral-free loan.",
    ],
    category: "Artisan / State",
    officialUrl: "https://pmvishwakarma.gov.in",
  },
  {
    id: "scheme-4",
    name: "Stand-Up India Scheme for Women & SC/ST",
    nameHindi: "स्टैंड-अप इंडिया योजना (महिला व SC/ST उद्यमी)",
    ministry: "Department of Financial Services, Ministry of Finance",
    maxAmount: 10000000,
    subsidyPct: 0,
    interestRate: "Lowest applicable rate of bank (MCLR + 3%)",
    eligibility: [
      "Women entrepreneurs or SC/ST individual entrepreneurs",
      "Setting up a greenfield (new) enterprise in manufacturing, services, agri-allied, or trading",
      "In non-individual enterprises, 51% shareholding held by SC/ST/Woman",
    ],
    description: "Facilitates bank loans between ₹10 Lakh and ₹1 Crore to at least one SC/ST and one Woman borrower per bank branch for setting up a greenfield enterprise.",
    keyBenefits: [
      "High ticket financing from ₹10 Lakh up to ₹1 Crore",
      "Composite loan covering both term loan and working capital",
      "Repayable in 7 years with maximum 18 months moratorium period",
      "Credit Guarantee Scheme for Stand-Up India (CGSSI) coverage",
    ],
    documentsRequired: [
      "Identity & Address proofs",
      "Project report with detailed financial projections",
      "Lease deed / ownership proof for factory/workshop premises",
      "Pollution NOC & Industry registrations",
    ],
    applySteps: [
      "Register on standupmitra.in portal.",
      "Select Lead District Manager (LDM) or scheduled commercial bank branch.",
      "Submit business plan and financial feasibility.",
      "Loan processed with pre-loan handholding support.",
    ],
    category: "MSME",
    officialUrl: "https://www.standupmitra.in",
  },
  {
    id: "scheme-5",
    name: "NABARD Rural Enterprise & SHG-Bank Linkage",
    nameHindi: "नाबार्ड ग्रामीण उद्यम व स्वयं सहायता समूह लिंकेज",
    ministry: "National Bank for Agriculture and Rural Development (NABARD)",
    maxAmount: 1500000,
    subsidyPct: 25,
    interestRate: "7.0% - 9.5% p.a.",
    eligibility: [
      "Rural micro entrepreneurs, Farmer Producer Organisations (FPOs), and Self-Help Groups (SHGs)",
      "Units involved in rural crafts, food processing, eco-packaging, and farm value addition",
    ],
    description: "Direct refinance and developmental grants supporting rural artisans, off-farm producer organizations, and micro-enterprises in villages and rural clusters.",
    keyBenefits: [
      "Subsidized interest rates with special women entrepreneur focus",
      "Support for exhibition stalls, marketing fairs, and cluster development",
      "Grant for technical skill training and design development",
    ],
    documentsRequired: [
      "SHG / FPO / Enterprise registration",
      "Bank account with clean repayment track record",
      "Project expenditure statement",
    ],
    applySteps: [
      "Contact District Development Manager (DDM) of NABARD in Jaipur district.",
      "Submit proposal through designated Regional Rural Bank (e.g. Rajasthan Marudhara Gramin Bank).",
    ],
    category: "NABARD",
    officialUrl: "https://www.nabard.org",
  },
];

export const initialBusinessPlan: BusinessPlan = {
  businessName: "Jaipur Heritage Handcrafted Products",
  ownerName: "Prashant Sharma",
  location: "Sanganer, Jaipur, Rajasthan",
  category: "Artisan MSME & Sustainable Textiles",
  capitalRequired: 250000,
  ownContribution: 100000,
  loanNeeded: 150000,
  targetAudience: "Eco-conscious urban consumers, local boutique stores, organic grocery chains, and corporate gifting clients.",
  pricingStrategy: "Cost-plus with 45-60% gross margin. Competitive wholesale tier for orders above 20 units.",
  costStructure: "Raw fabric: 35%, Natural dye & printing: 20%, Stitching labor: 20%, Packaging & logistics: 10%, Fixed utilities: 15%.",
  marketingChannels: ["Pragati Local Network Marketplace", "Direct WhatsApp Business Catalog", "Local Boutique Consignment", "Craft Melas & Exhibitions"],
  monthlyRevenueTarget: 60000,
  breakEvenTarget: "42 units of bags / month",
  milestoneGoals: [
    "Complete Mudra Kishor loan documentation for ₹1.5 Lakh working capital.",
    "Onboard 5 local wholesale suppliers on Pragati Network.",
    "Reach recurring monthly revenue of ₹75,000 by Month 6.",
    "Train 4 additional rural women tailors in high-finish bag stitching.",
  ],
  lastUpdated: "2026-09-04",
};

export const initialRoadmapSteps: RoadmapStep[] = [
  {
    id: "step-1",
    phase: 1,
    phaseName: "1. Business Setup & Registration",
    title: "Obtain Free Udyam MSME Certificate",
    description: "Register online on udyamregistration.gov.in using Aadhaar and PAN in 10 minutes to access all MSME benefits.",
    isCompleted: true,
    estimatedDays: 1,
    category: "Compliance",
    actionableLink: "/learn",
  },
  {
    id: "step-2",
    phase: 1,
    phaseName: "1. Business Setup & Registration",
    title: "Open Business Current Account",
    description: "Open dedicated current bank account linked with UPI QR code to keep personal and business money separate.",
    isCompleted: true,
    estimatedDays: 3,
    category: "Setup",
    actionableLink: "/finance",
  },
  {
    id: "step-3",
    phase: 2,
    phaseName: "2. Supplier Sourcing & Setup",
    title: "Finalize Fabric & Raw Material Suppliers",
    description: "Connect with local cotton mills and dye suppliers on Pragati Network to lock in wholesale rates.",
    isCompleted: true,
    estimatedDays: 5,
    category: "Supply",
    actionableLink: "/network",
  },
  {
    id: "step-4",
    phase: 2,
    phaseName: "2. Supplier Sourcing & Setup",
    title: "Set Up Quality Stitching & Packaging Station",
    description: "Install sewing machines and organize raw inventory with designated low-stock safety thresholds.",
    isCompleted: true,
    estimatedDays: 4,
    category: "Setup",
    actionableLink: "/my-business?tab=stock",
  },
  {
    id: "step-5",
    phase: 3,
    phaseName: "3. Start Selling & Tracking Khata",
    title: "Record First 10 Customer Sales in Khata",
    description: "Issue digital bills for every sale, update customer records, and review daily profit calculation.",
    isCompleted: true,
    estimatedDays: 7,
    category: "Sales",
    actionableLink: "/my-business?tab=sales",
  },
  {
    id: "step-6",
    phase: 3,
    phaseName: "3. Start Selling & Tracking Khata",
    title: "Track All Business Expenses Regularly",
    description: "Enter raw material, artisan wages, and packaging costs daily to see real cash in hand vs paper profit.",
    isCompleted: true,
    estimatedDays: 3,
    category: "Supply",
    actionableLink: "/my-business?tab=money",
  },
  {
    id: "step-7",
    phase: 4,
    phaseName: "4. Financing & Working Capital",
    title: "Apply for Mudra Kishor / PM Vishwakarma Credit",
    description: "Submit your Pragati Business Plan and quotation to bank for ₹1.5 Lakh low-interest loan.",
    isCompleted: false,
    estimatedDays: 14,
    category: "Compliance",
    actionableLink: "/loans-schemes",
  },
  {
    id: "step-8",
    phase: 5,
    phaseName: "5. Customer Retention & B2B Expansion",
    title: "Establish 3 Recurring Boutique / Retail Tie-ups",
    description: "Send enquiries and product catalogs to local boutiques and gift stores via Pragati Network.",
    isCompleted: false,
    estimatedDays: 20,
    category: "Growth",
    actionableLink: "/network",
  },
  {
    id: "step-9",
    phase: 6,
    phaseName: "6. Scale & Sustainable Growth",
    title: "Achieve ₹75,000+ Monthly Consistent Revenue",
    description: "Maintain 45%+ net margin, automate inventory replenishment, and train 4 additional local artisans.",
    isCompleted: false,
    estimatedDays: 45,
    category: "Growth",
    actionableLink: "/reports",
  },
];

export const initialLearnLessons: LearnLesson[] = [
  {
    id: "lesson-1",
    category: "Money Basics",
    title: "What is Working Capital? (कार्यशील पूंजी क्या है?)",
    titleHindi: "कार्यशील पूंजी क्या है और यह क्यों जरूरी है?",
    durationMinutes: 5,
    summary: "Understand the difference between fixed investment and the daily cash needed to buy raw material and pay wages.",
    content: [
      "Working capital (कार्यशील पूंजी) is the money your business needs every single day to stay open and operating smoothly.",
      "Example: When you buy cloth for ₹5,000 and pay ₹2,000 to tailors, you need ₹7,000 in hand before the customer buys your bags and pays you ₹12,000.",
      "If all your money is locked in unsold stock or pending customer credit (Udhaar), you cannot buy fresh raw material — this is called a Working Capital Crunch.",
      "Golden Rule: Always keep at least 1.5 to 2 months of operating expenses in cash or bank balance before planning new expansions.",
    ],
    keyTakeaways: [
      "Working capital = Daily operating cash required.",
      "Never lock 100% of your capital in fixed machinery.",
      "Collect customer payments on time to keep the cash rotation healthy.",
    ],
    isCompleted: true,
  },
  {
    id: "lesson-2",
    category: "Money Basics",
    title: "Understanding Profit vs Cash Flow (मुनाफा बनाम नकद प्रवाह)",
    titleHindi: "मुनाफा और जेब में नकद का हिसाब",
    durationMinutes: 6,
    summary: "Why a business can show profit on paper but still run out of cash to pay bills.",
    content: [
      "Profit (मुनाफा) = Total Sales Revenue minus Total Expenses incurred.",
      "Cash Flow (नकद प्रवाह) = Actual cash received in your hand minus actual cash paid out.",
      "If you sell goods worth ₹20,000 on 30-day credit, your account book shows ₹8,000 profit today, but your bank balance is ₹0 until the customer pays.",
      "In Pragati Money & Khata, we track both your Sales Ledger and real Cash Balance so you never face a surprise shortage.",
    ],
    keyTakeaways: [
      "Paper profit does not pay suppliers; cash in hand does.",
      "Limit Udhaar (customer credit) to trusted repeat buyers only.",
      "Track every small daily kharcha immediately.",
    ],
    isCompleted: true,
  },
  {
    id: "lesson-3",
    category: "Sales & Marketing",
    title: "Pricing for 45%+ Margin (सही दाम कैसे तय करें?)",
    titleHindi: "उत्पाद की सही कीमत तय करने का फॉर्मूला",
    durationMinutes: 7,
    summary: "How to calculate your true unit cost including wastage, electricity, packaging, and your own labor.",
    content: [
      "Many small business owners forget to include their own time and shop rent when deciding prices.",
      "Step 1: Calculate Direct Material Cost (Cloth + Thread + Dyes + Buttons).",
      "Step 2: Add Direct Labor (Stitching time @ fair wage).",
      "Step 3: Add Overhead per item (Packaging tag ₹5 + Electricity ₹10 + Transport ₹15).",
      "Step 4: Add your target profit margin (40% to 60%). Example: If total cost is ₹280, selling price should be ₹480 - ₹520.",
    ],
    keyTakeaways: [
      "Never sell at cost price hoping to make profit 'later'.",
      "Always count packaging and wastage in the initial cost.",
      "Use Pragati Business Simulator to test pricing scenarios before setting rates.",
    ],
    isCompleted: false,
  },
  {
    id: "lesson-4",
    category: "Operations & Stock",
    title: "Smart Inventory & Low-Stock Alerts (स्टॉक का सही प्रबंधन)",
    titleHindi: "स्टॉक का सही प्रबंधन और कमी से बचना",
    durationMinutes: 5,
    summary: "Avoid stockouts during festivals and prevent dead capital in unsold goods.",
    content: [
      "Having too much stock locks your hard-earned money in dead inventory.",
      "Having too little stock means you turn away paying customers and lose trust.",
      "Set a 'Low-Stock Threshold' for every item. For example, if it takes 4 days for your supplier to deliver cotton fabric, set your safety threshold at 10 meters.",
      "Pragati automatically alerts you on Home and Stock tab whenever any product touches the threshold.",
    ],
    keyTakeaways: [
      "Set safety thresholds on all fast-moving items.",
      "Re-order raw material before stock reaches zero.",
      "Use 'Stock Mangwayein' to find nearby suppliers on Pragati Network instantly.",
    ],
    isCompleted: false,
  },
  {
    id: "lesson-5",
    category: "Digital & Schemes",
    title: "How to Apply for Mudra & PMEGP Loans (सरकारी लोन कैसे लें?)",
    titleHindi: "मुद्रा व PMEGP लोन के लिए सही तैयारी",
    durationMinutes: 8,
    summary: "Step-by-step checklist to get your loan sanctioned without paying middlemen.",
    content: [
      "Government schemes like Mudra Shishu/Kishor and PMEGP are designed specifically for micro enterprises without requiring collateral.",
      "Step 1: Get your Udyam Registration certificate (Free on udyamregistration.gov.in).",
      "Step 2: Prepare a clear 1-page Business Plan with estimated monthly sales, expenses, and machinery quotations.",
      "Step 3: Approach your local Gramin Bank or Public Sector Bank branch manager politely with your Pragati Business Plan.",
      "Never pay any commission or unofficial fees to middlemen. Report corruption on 1912 / KVIC helpline.",
    ],
    keyTakeaways: [
      "Udyam registration and clean business plan are the key requirements.",
      "Collateral-free loans up to ₹10 Lakh are your legal right under Mudra scheme.",
      "Bankers approve applications that show realistic calculations and clear customer demand.",
    ],
    isCompleted: false,
  },
];

export const initialSimulatorInputs: SimulatorInputs = {
  investment: 120000,
  monthlyProduction: 100,
  unitCost: 280,
  sellingPrice: 480,
  fixedExpenses: 9500,
};
