/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as BusinessIdeasRouteImport } from './routes/business-ideas'
import { Route as BusinessSimulatorRouteImport } from './routes/business-simulator'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LoansSchemesRouteImport } from './routes/loans-schemes'
import { Route as LocalOpportunitiesRouteImport } from './routes/local-opportunities'
import { Route as MyBusinessRouteImport } from './routes/my-business'
import { Route as MyBusinessPlanRouteImport } from './routes/my-business-plan'
import { Route as MyRoadmapRouteImport } from './routes/my-roadmap'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as StartABusinessRouteImport } from './routes/start-a-business'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIdeasRoute = BusinessIdeasRouteImport.update({
  id: '/business-ideas',
  path: '/business-ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSimulatorRoute = BusinessSimulatorRouteImport.update({
  id: '/business-simulator',
  path: '/business-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansSchemesRoute = LoansSchemesRouteImport.update({
  id: '/loans-schemes',
  path: '/loans-schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalOpportunitiesRoute = LocalOpportunitiesRouteImport.update({
  id: '/local-opportunities',
  path: '/local-opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBusinessRoute = MyBusinessRouteImport.update({
  id: '/my-business',
  path: '/my-business',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBusinessPlanRoute = MyBusinessPlanRouteImport.update({
  id: '/my-business-plan',
  path: '/my-business-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoadmapRoute = MyRoadmapRouteImport.update({
  id: '/my-roadmap',
  path: '/my-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const StartABusinessRoute = StartABusinessRouteImport.update({
  id: '/start-a-business',
  path: '/start-a-business',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/business-ideas': typeof BusinessIdeasRoute
  '/business-simulator': typeof BusinessSimulatorRoute
  '/finance': typeof FinanceRoute
  '/learn': typeof LearnRoute
  '/loans-schemes': typeof LoansSchemesRoute
  '/local-opportunities': typeof LocalOpportunitiesRoute
  '/my-business': typeof MyBusinessRoute
  '/my-business-plan': typeof MyBusinessPlanRoute
  '/my-roadmap': typeof MyRoadmapRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/start-a-business': typeof StartABusinessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/business-ideas': typeof BusinessIdeasRoute
  '/business-simulator': typeof BusinessSimulatorRoute
  '/finance': typeof FinanceRoute
  '/learn': typeof LearnRoute
  '/loans-schemes': typeof LoansSchemesRoute
  '/local-opportunities': typeof LocalOpportunitiesRoute
  '/my-business': typeof MyBusinessRoute
  '/my-business-plan': typeof MyBusinessPlanRoute
  '/my-roadmap': typeof MyRoadmapRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/start-a-business': typeof StartABusinessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/business-ideas': typeof BusinessIdeasRoute
  '/business-simulator': typeof BusinessSimulatorRoute
  '/finance': typeof FinanceRoute
  '/learn': typeof LearnRoute
  '/loans-schemes': typeof LoansSchemesRoute
  '/local-opportunities': typeof LocalOpportunitiesRoute
  '/my-business': typeof MyBusinessRoute
  '/my-business-plan': typeof MyBusinessPlanRoute
  '/my-roadmap': typeof MyRoadmapRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/start-a-business': typeof StartABusinessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-assistant'
    | '/business-ideas'
    | '/business-simulator'
    | '/finance'
    | '/learn'
    | '/loans-schemes'
    | '/local-opportunities'
    | '/my-business'
    | '/my-business-plan'
    | '/my-roadmap'
    | '/network'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/start-a-business'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-assistant'
    | '/business-ideas'
    | '/business-simulator'
    | '/finance'
    | '/learn'
    | '/loans-schemes'
    | '/local-opportunities'
    | '/my-business'
    | '/my-business-plan'
    | '/my-roadmap'
    | '/network'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/start-a-business'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-assistant'
    | '/business-ideas'
    | '/business-simulator'
    | '/finance'
    | '/learn'
    | '/loans-schemes'
    | '/local-opportunities'
    | '/my-business'
    | '/my-business-plan'
    | '/my-roadmap'
    | '/network'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/start-a-business'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiAssistantRoute: typeof AiAssistantRoute
  BusinessIdeasRoute: typeof BusinessIdeasRoute
  BusinessSimulatorRoute: typeof BusinessSimulatorRoute
  FinanceRoute: typeof FinanceRoute
  LearnRoute: typeof LearnRoute
  LoansSchemesRoute: typeof LoansSchemesRoute
  LocalOpportunitiesRoute: typeof LocalOpportunitiesRoute
  MyBusinessRoute: typeof MyBusinessRoute
  MyBusinessPlanRoute: typeof MyBusinessPlanRoute
  MyRoadmapRoute: typeof MyRoadmapRoute
  NetworkRoute: typeof NetworkRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  StartABusinessRoute: typeof StartABusinessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-ideas': {
      id: '/business-ideas'
      path: '/business-ideas'
      fullPath: '/business-ideas'
      preLoaderRoute: typeof BusinessIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-simulator': {
      id: '/business-simulator'
      path: '/business-simulator'
      fullPath: '/business-simulator'
      preLoaderRoute: typeof BusinessSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans-schemes': {
      id: '/loans-schemes'
      path: '/loans-schemes'
      fullPath: '/loans-schemes'
      preLoaderRoute: typeof LoansSchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-opportunities': {
      id: '/local-opportunities'
      path: '/local-opportunities'
      fullPath: '/local-opportunities'
      preLoaderRoute: typeof LocalOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-business': {
      id: '/my-business'
      path: '/my-business'
      fullPath: '/my-business'
      preLoaderRoute: typeof MyBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-business-plan': {
      id: '/my-business-plan'
      path: '/my-business-plan'
      fullPath: '/my-business-plan'
      preLoaderRoute: typeof MyBusinessPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-roadmap': {
      id: '/my-roadmap'
      path: '/my-roadmap'
      fullPath: '/my-roadmap'
      preLoaderRoute: typeof MyRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-a-business': {
      id: '/start-a-business'
      path: '/start-a-business'
      fullPath: '/start-a-business'
      preLoaderRoute: typeof StartABusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiAssistantRoute: AiAssistantRoute,
  BusinessIdeasRoute: BusinessIdeasRoute,
  BusinessSimulatorRoute: BusinessSimulatorRoute,
  FinanceRoute: FinanceRoute,
  LearnRoute: LearnRoute,
  LoansSchemesRoute: LoansSchemesRoute,
  LocalOpportunitiesRoute: LocalOpportunitiesRoute,
  MyBusinessRoute: MyBusinessRoute,
  MyBusinessPlanRoute: MyBusinessPlanRoute,
  MyRoadmapRoute: MyRoadmapRoute,
  NetworkRoute: NetworkRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  StartABusinessRoute: StartABusinessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
